# Copyright (C) 2014-2016 The CyanogenMod Project
# Copyright (C) 2017-2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

<<<<<<< HEAD
<<<<<<< HEAD:tblte/BoardConfigVendor.mk
# This file is generated by device/samsung/tblte/setup-makefiles.sh
=======
# This file is generated by device/samsung/lentis-common/setup-makefiles.sh
>>>>>>> 09647202... Add/update kccat6, lentislte*, tblte and trlte*:lentis-common/BoardConfigVendor.mk
=======
# This file is generated by device/samsung/tblte/setup-makefiles.sh
>>>>>>> 09647202... Add/update kccat6, lentislte*, tblte and trlte*

