# Copyright (C) 2014-2016 The CyanogenMod Project
# Copyright (C) 2017-2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/trlteduos/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/trlteduos/proprietary/blobs/duos/bin/efsks:system/blobs/duos/vendor/bin/efsks \
    vendor/samsung/trlteduos/proprietary/blobs/duos/bin/ks:system/blobs/duos/vendor/bin/ks \
    vendor/samsung/trlteduos/proprietary/blobs/duos/bin/mdm_helper:system/blobs/duos/vendor/bin/mdm_helper \
    vendor/samsung/trlteduos/proprietary/blobs/duos/bin/mdm_helper_proxy:system/blobs/duos/vendor/bin/mdm_helper_proxy \
    vendor/samsung/trlteduos/proprietary/blobs/duos/bin/qcks:system/blobs/duos/vendor/bin/qcks \
    vendor/samsung/trlteduos/proprietary/blobs/duos/bin/qmuxd:system/blobs/duos/vendor/bin/qmuxd \
    vendor/samsung/trlteduos/proprietary/blobs/duos/lib/libprotobuf-cpp-full.so:system/blobs/duos/vendor/lib/libprotobuf-cpp-full.so \
    vendor/samsung/trlteduos/proprietary/blobs/duos/lib/libsec-ril-dsds.so:system/blobs/duos/vendor/lib/libsec-ril-dsds.so \
    vendor/samsung/trlteduos/proprietary/blobs/duos/lib/libsec-ril.so:system/blobs/duos/vendor/lib/libsec-ril.so \
    vendor/samsung/trlteduos/proprietary/blobs/duos/vendor/lib/libconfigdb.so:system/blobs/duos/vendor/lib/libconfigdb.so \
    vendor/samsung/trlteduos/proprietary/blobs/duos/vendor/lib/libdiag.so:system/blobs/duos/vendor/lib/libdiag.so \
    vendor/samsung/trlteduos/proprietary/blobs/duos/vendor/lib/libdsutils.so:system/blobs/duos/vendor/lib/libdsutils.so \
    vendor/samsung/trlteduos/proprietary/blobs/duos/vendor/lib/libflp.so:system/blobs/duos/vendor/lib/libflp.so \
    vendor/samsung/trlteduos/proprietary/blobs/duos/vendor/lib/libidl.so:system/blobs/duos/vendor/lib/libidl.so \
    vendor/samsung/trlteduos/proprietary/blobs/duos/vendor/lib/liblbs_core.so:system/blobs/duos/vendor/lib/liblbs_core.so \
    vendor/samsung/trlteduos/proprietary/blobs/duos/vendor/lib/libmdmdetect.so:system/blobs/duos/vendor/lib/libmdmdetect.so \
    vendor/samsung/trlteduos/proprietary/blobs/duos/vendor/lib/libnetmgr.so:system/blobs/duos/vendor/lib/libnetmgr.so \
    vendor/samsung/trlteduos/proprietary/blobs/duos/vendor/lib/libqcci_legacy.so:system/blobs/duos/vendor/lib/libqcci_legacy.so \
    vendor/samsung/trlteduos/proprietary/blobs/duos/vendor/lib/libqmi.so:system/blobs/duos/vendor/lib/libqmi.so \
    vendor/samsung/trlteduos/proprietary/blobs/duos/vendor/lib/libqmi_cci.so:system/blobs/duos/vendor/lib/libqmi_cci.so \
    vendor/samsung/trlteduos/proprietary/blobs/duos/vendor/lib/libqmi_client_qmux.so:system/blobs/duos/vendor/lib/libqmi_client_qmux.so \
    vendor/samsung/trlteduos/proprietary/blobs/duos/vendor/lib/libqmi_common_so.so:system/blobs/duos/vendor/lib/libqmi_common_so.so \
    vendor/samsung/trlteduos/proprietary/blobs/duos/vendor/lib/libqmi_csi.so:system/blobs/duos/vendor/lib/libqmi_csi.so \
    vendor/samsung/trlteduos/proprietary/blobs/duos/vendor/lib/libqmi_encdec.so:system/blobs/duos/vendor/lib/libqmi_encdec.so \
    vendor/samsung/trlteduos/proprietary/blobs/duos/vendor/lib/libqmiservices.so:system/blobs/duos/vendor/lib/libqmiservices.so \
    vendor/samsung/trlteduos/proprietary/blobs/duos/vendor/lib/libril-qcril-hook-oem.so:system/blobs/duos/vendor/lib/libril-qcril-hook-oem.so
    
PRODUCT_PACKAGES += \
    cbd
